name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_ed25519 -p ${{ secrets.EC2_PORT }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu
          echo "export SECRET_KEY='$(openssl rand -hex 40)'" > .DJANGO_SECRET_KEY
          source .DJANGO_SECRET_KEY
          sudo apt update -y
          sudo apt upgrade -y
          cd /home/ubuntu/analytixpress
          git pull origin main
          source ./.venv/bin/activate
          pip install -r requirements.txt
          python manage.py makemigrations
          python manage.py migrate
          npm install -y
          npm run build -y
          python manage.py collectstatic --noinput
          gunicorn -c config/gunicorn/prod.py
          sudo systemctl restart nginx
        EOF
